### ISSUE TITLE
Emitance plot

### ISSUE THREAD

**Issue by eccortes95** [hibtc/madgui#32]
The emittance computed and plotted for the hht2 HIT Model appears to be completely wrong.

**Comment by eccortes95** [comment]
I also discovered that the sigma matrix is no more available in tabular view, when using the info feature. I get following error:
Traceback (most recent call last):
  File "/home/cristopher/HIT/madgui/src/madgui/widget/params.py", line 334, in update
    self.currentWidget().update(**self.kw)
  File "/home/cristopher/HIT/madgui/src/madgui/widget/params.py", line 114, in update
    self.rows = self.fetch(**self.fetch_args)
  File "/home/cristopher/HIT/madgui/src/madgui/widget/elementinfo.py", line 130, in _fetch_sigma
    return self.model.get_elem_sigma(elem_index)
  File "/home/cristopher/HIT/madgui/src/madgui/model/madx.py", line 434, in get_elem_sigma
    for i in range(6)
  File "/home/cristopher/HIT/madgui/src/madgui/model/madx.py", line 434, in <listcomp>
    for i in range(6)
  File "/home/cristopher/HIT/madgui/src/madgui/model/madx.py", line 433, in <listcomp>
    for j in range(6)]
  File "/home/cristopher/anaconda3/envs/madgui/lib/python3.7/site-packages/cpymad/madx.py", line 537, in __getitem__
    return self._data[name.lower()]
KeyError: 'sig11'

**Comment by coldfix** [comment]
Fixed by #34 and de488e1168b932f9586bda1621988dd73ebc3c28, respectively.
