### ISSUE TITLE
Unicode error starting madqt with "madqt -h"

### ISSUE THREAD

**Issue by DavidSagan** [hibtc/madgui#9]
On Linux tried to start madqt with the -h option and got the following error

XXX:erpsim1:~/dcs16/TaoGui/madqt> madqt -h
failed to get the current screen resources
Qt: Could not determine keyboard configuration data from X server, will use hard-coded keymap configuration.
Traceback (most recent call last):
  File "/home/dcs16/dcs16/usr_local/bin/madqt", line 11, in <module>
    load_entry_point('MadQt==0.0.0', 'gui_scripts', 'madqt')()
  File "/home/dcs16/dcs16/usr_local/lib/python3.5/site-packages/MadQt-0.0.0-py3.5.egg/madqt/core/app.py", line 65, in main
    opts = docopt(__doc__, args, version=__version__)
  File "/home/dcs16/dcs16/usr_local/lib/python3.5/site-packages/docopt.py", line 575, in docopt
    extras(help, version, argv, doc)
  File "/home/dcs16/dcs16/usr_local/lib/python3.5/site-packages/docopt.py", line 481, in extras
    print(doc.strip("\n"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 385-386: ordinal not in range(128)

**Comment by coldfix** [comment]
What is the output of `python -c 'import sys; print(sys.stdout.encoding)` ?

**Comment by DavidSagan** [comment]
```
XXX:erpsim1:~/dcs16/TaoGui/test> python -c 'import sys; print(sys.stdout.encoding)'
ANSI_X3.4-1968
```

**Comment by coldfix** [comment]
Okay. Is it safe to have UTF-8 output in your terminal? If so, I will add a wrapper. Other option is to call it as:

```
PYTHONIOENCODING='utf8' madqt -h
```

**Comment by DavidSagan** [comment]
As far as I know utf-8 is fine for my terminal.
